AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for the Versioneye Task
Resources:
  SecretsStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'secrets.ve.eacg.de'
      VersioningConfiguration:
        Status: Enabled
  VersioneyeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  VersioneyeTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: secure-versioneye
          Image:  '959013096341.dkr.ecr.eu-central-1.amazonaws.com/ve-eacg/app:1.0.1'
          Memory: '500'
          Essential: 'true'
          PortMappings:
            - ContainerPort: '8080'
              HostPort: '8080'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'VersioneyeLogGroup'
              awslogs-region: !Ref 'AWS::Region'
          Environment:
            - Name: SECRETS_BUCKET_NAME
              Value: !Ref 'SecretsStoreBucket'
Outputs:
  SecretsStoreBucket:
    Description: The S3 bucket name where the secrets are stored
    Value: !Ref 'SecretsStoreBucket'
  VersioneyeTaskDefinition:
    Description: The WordPress ECS Task Definition ARN
    Value: !Ref 'VersioneyeTaskDefinition'
